services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"  
    volumes:
      - ./api:/api 
      - ./data:/api/data  # uses the data files locally since docker image doesnt contain data files
    command: python main.py  # Start the app
