name: Python application

on:
  push:
    branches:
      - main  # Target Production environment
      - staging  # Target Staging environment
      - develop  # Target Development environment

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Clear pip cache
        run: |
          rm -rf ~/.cache/pip  # Ensure cache is cleared before installing dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools>=70.0.0
          pip install --no-cache-dir flake8 safety  # Use --no-cache-dir to ensure no cache is used
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          
      - name: Check for dependency vulnerabilities
        run: |
          safety check --full-report

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  staging: 
    needs: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools>=70.0.0
          pip install --no-cache-dir flake8 pytest pytest-cov fastapi uvicorn safety
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
          
      - name: Check for dependency vulnerabilities
        run: |
          safety check --full-report

      - name: Start API server
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}
        run: |
          python api/main.py &  # Adjust the path to your server script
          sleep 5  # Allow time for the server to start

      - name: Test with pytest
        env:
          API_KEY_1: ${{ secrets.API_KEY_1 }}
          API_KEY_2: ${{ secrets.API_KEY_2 }}
        run: |
          coverage run -m pytest

      - name: Run code coverage
        if: always()
        run: |
          coverage xml
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          coverage report --fail-under=80

      - name: Store coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
        if: ${{ failure() }}

  deploy:
    needs: staging 
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying to the specified environment"
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create image if needed and start containers in Docker
        run: |
          docker-compose up -d --build

          
    #commented out to test the deployment
    # environment:
    #   name: ${{ github.ref_name == 'main' && 'Production' || github.ref_name == 'staging' && 'Staging' || 'Development' }}

  
